### ISSUE TITLE
Saferoom Extract issue

### ISSUE THREAD

**Issue by EduardoHM98** [dwesterwick/SPTQuestingBots#19]
Hello, 

I know that this issue was supposed to have been fixed on v0.4.2, but I'm running v0.5.0 and I've just run across it twice in a row.

I got a weekly quest to use the Saferoom extract 3 times, before this I'd never used it. First attempt worked out fine, but the second attempt resulted in me getting stuck inside the safe room after closing the door and having to ALT-F4, and on the third I got lucky by having a PMC open the door shortly after I closed it, allowing me to use another extract.

I noticed there's a folder with the mod's logs, so I'm including the logs of both of these runs in which I had the issue.

[Interchange_133600988918402738_assignments.csv](https://github.com/dwesterwick/SPTQuestingBots/files/15298983/Interchange_133600988918402738_assignments.csv)
[Interchange_133600988918402738_quests.csv](https://github.com/dwesterwick/SPTQuestingBots/files/15298986/Interchange_133600988918402738_quests.csv)
[Interchange_133600895639711408_assignments.csv](https://github.com/dwesterwick/SPTQuestingBots/files/15298987/Interchange_133600895639711408_assignments.csv)
[Interchange_133600895639711408_quests.csv](https://github.com/dwesterwick/SPTQuestingBots/files/15298988/Interchange_133600895639711408_quests.csv)

If necessary I can send my mods list, let me know. Thanks!

**Comment by dwesterwick** [comment]
I've confirmed this can happen when using mods like Open Sesame that add new actions to door context menus. I assume you're using that mod or something similar?

I'll include a bug fix in the next release.

**Comment by EduardoHM98** [comment]
> I've confirmed this can happen when using mods like Open Sesame that add new actions to door context menus. I assume you're using that mod or something similar?
> 
> I'll include a bug fix in the next release.

Not Open Sesame, but I am using DrakiaXYZ's Search Open Containers which does add a "search" action to open containers' context menus, though nothing on doors.

Relating to doors specifically the only mod I'm using is Gilded Key Storage, though it's just a container for keys and as far as I can tell doesn't change door interactions.

Hope this helps!
