### ISSUE TITLE
Bots get stuck on open door

### ISSUE THREAD

**Issue by MonstraG** [dwesterwick/SPTQuestingBots#25]
Several bots within each other get stuck on this door in Customs, in the medical building. They eventually leave.

![image](https://github.com/dwesterwick/SPTQuestingBots/assets/17963791/eb67fabe-8af6-43ca-acee-67282b4b4dc5)

**Comment by dwesterwick** [comment]
This happens even with vanilla EFT. Bot pathing issues have been a major annoyance since EFT 0.14.x, and it's nothing that Questing Bots is causing itself.
