### ISSUE TITLE
Bots falling through floor (0.5.1)

### ISSUE THREAD

**Issue by teddyursa** [dwesterwick/SPTQuestingBots#26]
![Uploading Screenshot (60).png…]()
Any way to combat bots falling through the floor with this otherwise amazing mod? (0.5.1 A3)

When I die in FIKA and watch my boys, I notice bots falling through the floor which ends up making the raid too easy because pretty much most of the spawns (Donuts/SWAG) are under the map thousands of meters away XD

I run SAIN/QB/LB/SWAG-Donuts , and it seems with FIKA if I die early....spawns stop, and bots go through the floor which produces a lame raid for spectating [and for my fika comrades]

Would love to nail down why this happens and if it's QB related.

Edit: I'm also not sure if I should disable -no despawns- to prevent this? I see no documentation on a FIKA host dieing, and how that raid will spawn stuff with the raid hoster dead.

edit 2 : PMCS end up phased through geometry too while i'm spectating my bois while dead. Just had a woods raid and a PMC was phased under ZB14. Same for a reserve spectate. No idea if this is QB or ....something else.

**Comment by dwesterwick** [comment]
Unless you're able to reproduce this issue without Fika and without any other spawning mod, I'm not able to provide support. I've never experienced this problem, so I would need to understand how to reproduce it with only Questing Bots and its dependencies. Sorry.
