### ISSUE TITLE
Unhandled Promise Rejection in console during bot generation

### ISSUE THREAD

**Issue by PeriodicOccupancy** [dwesterwick/SPTQuestingBots#33]
I'm unsure what's causing this and if it's actually affecting my game at all, but I get 
`[Client Request] /QuestingBots/GenerateBot/0?retry=2
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".`
In the console frequently while in raid. 

I'm using SPT 3.9.4 and the most recent version of SAIN, looting bots, Swag, and ofc questing bots as well as all of their pre-reqs. I'm also using The Painter, and am wondering if maybe it's quests are causing the issue.

**Comment by PeriodicOccupancy** [comment]
This might not be an issue with questing bots, and might be an issue with bot spawning, as I've now noticed no scavs are spawning

**Comment by PeriodicOccupancy** [comment]
Reverting to 3.9.3 solves the issue.

**Comment by dwesterwick** [comment]
The `/QuestingBots/GenerateBot` endpoint just reroutes the bot generation request. The only thing it does while intercepting it is modify the server's PScav conversion chance. If there are errors downstream of this, it's caused by another mod or broken SPT install.

I just updated to SPT 3.9.4, and I'm not experiencing this problem.

**Comment by PeriodicOccupancy** [comment]
yea by the end of it I figured it wasn't your mod, I'm guessing it's something that changed in 3.9.4 that caused an issue with Swag most likely, as I don't have any other mods that affect spawns, sorry if I wasted your time. Appreciate all the work you do
