### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Fuckingnameless** [dwesterwick/SPTQuestingBots#35]
how can i update to the repo version just drop the bepynx folder and configs will regerate?

Thanks for the excellent work.

**Comment by dwesterwick** [comment]
The repo version is for testing only. Please use the official version posted on [https://hub.sp-tarkov.com/files/file/1534-questing-bots/](https://hub.sp-tarkov.com/files/file/1534-questing-bots/) for normal usage.
