### ISSUE TITLE
Allow the Server and Client to Run on Different Machines

### ISSUE THREAD

**Issue by dwesterwick** [dwesterwick/SPTQuestingBots#9]
Currently, a relative path is shared from the server to the client via an HTTP request for the client to know where quest files are and where to save log files. This approach only works if both are on the same PC. 

To accomplish this, the following changes are needed:
* Do not exchange relative paths between the server and client. The server should only access server files, and the client should only access client files. 
* Quest files need to be moved into a folder where the client DLL lives
* Log files need to be saved in a folder where the client DLL lives
* The build script needs to be updated to change where the quest files are stored in the ZIP file
* The basic JSON validation of quest files when the server starts needs to be disabled

Optional changes:
* Some kind of code should be added to check for old files and either do some kind of automatic migration or simply warn the user

**Comment by kapdon** [comment]
- I don't believe you can get around exchanging the config file as both the server and client so far uses this file and rewriting is a lot of work with no easy fix. I think the concept of path requests can be removed completely. Hardcoded/AssemblyPath for both the config or data directories you need. You control the project structure, that will will reduce fragility. Fuck network errors.
- LGTM on the rest.

**Comment by kapdon** [comment]
one additional thing, I've learned after making this modification but have been too lazy to fix it as it is not a personal issue.

It's better to use `Directory.CreateDirectory(AppDomain.CurrentDomain.BaseDirectory + "/BepInEx/plugins/DanW-SPTQuestingBots/");` 
than what I originally did.
```
string dllPath = Assembly.GetExecutingAssembly().Location;
string directoryPath = Path.GetDirectoryName(dllPath);
```
if the user somehow move the dll it will look for relative path from that directory and will cause loading errors.
 
personally I think all plugins should follow the `pluginfolder/plugin.dll` structure so using the `AppDomain.CurrentDomain.BaseDirectory` of EFT.exe is less fragile.

**Comment by dwesterwick** [comment]
Thanks for the tip, that makes sense.

Feel free to make a PR in the 0.5.1-DEV branch if you'd like to help push this change along!
